//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.WebClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ICodeService")]
    public interface ICodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/InserCodeService", ReplyAction="http://tempuri.org/ICodeService/InserCodeServiceResponse")]
        string InserCodeService(string codeData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/GetCodeService", ReplyAction="http://tempuri.org/ICodeService/GetCodeServiceResponse")]
        string GetCodeService(string codeID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeServiceChannel : app.WebClient.ServiceReference2.ICodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeServiceClient : System.ServiceModel.ClientBase<app.WebClient.ServiceReference2.ICodeService>, app.WebClient.ServiceReference2.ICodeService {
        
        public CodeServiceClient() {
        }
        
        public CodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InserCodeService(string codeData) {
            return base.Channel.InserCodeService(codeData);
        }
        
        public string GetCodeService(string codeID) {
            return base.Channel.GetCodeService(codeID);
        }
    }
}
