#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.WebClient.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iwayward")]
	public partial class codeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCODE(CODE instance);
    partial void UpdateCODE(CODE instance);
    partial void DeleteCODE(CODE instance);
    #endregion
		
		public codeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iwaywardConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public codeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public codeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public codeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public codeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CODE> CODE
		{
			get
			{
				return this.GetTable<CODE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CODE")]
	public partial class CODE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeID;
		
		private string _CodeName;
		
		private string _CodeFatherID;
		
		private System.Nullable<int> _CodeIndex;
		
		private string _CodeValue1;
		
		private string _CodeValue2;
		
		private string _CodeValue3;
		
		private string _CodeMark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeIDChanging(string value);
    partial void OnCodeIDChanged();
    partial void OnCodeNameChanging(string value);
    partial void OnCodeNameChanged();
    partial void OnCodeFatherIDChanging(string value);
    partial void OnCodeFatherIDChanged();
    partial void OnCodeIndexChanging(System.Nullable<int> value);
    partial void OnCodeIndexChanged();
    partial void OnCodeValue1Changing(string value);
    partial void OnCodeValue1Changed();
    partial void OnCodeValue2Changing(string value);
    partial void OnCodeValue2Changed();
    partial void OnCodeValue3Changing(string value);
    partial void OnCodeValue3Changed();
    partial void OnCodeMarkChanging(string value);
    partial void OnCodeMarkChanged();
    #endregion
		
		public CODE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeID", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeID
		{
			get
			{
				return this._CodeID;
			}
			set
			{
				if ((this._CodeID != value))
				{
					this.OnCodeIDChanging(value);
					this.SendPropertyChanging();
					this._CodeID = value;
					this.SendPropertyChanged("CodeID");
					this.OnCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeName", DbType="VarChar(100)")]
		public string CodeName
		{
			get
			{
				return this._CodeName;
			}
			set
			{
				if ((this._CodeName != value))
				{
					this.OnCodeNameChanging(value);
					this.SendPropertyChanging();
					this._CodeName = value;
					this.SendPropertyChanged("CodeName");
					this.OnCodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeFatherID", DbType="VarChar(32)")]
		public string CodeFatherID
		{
			get
			{
				return this._CodeFatherID;
			}
			set
			{
				if ((this._CodeFatherID != value))
				{
					this.OnCodeFatherIDChanging(value);
					this.SendPropertyChanging();
					this._CodeFatherID = value;
					this.SendPropertyChanged("CodeFatherID");
					this.OnCodeFatherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeIndex", DbType="Int")]
		public System.Nullable<int> CodeIndex
		{
			get
			{
				return this._CodeIndex;
			}
			set
			{
				if ((this._CodeIndex != value))
				{
					this.OnCodeIndexChanging(value);
					this.SendPropertyChanging();
					this._CodeIndex = value;
					this.SendPropertyChanged("CodeIndex");
					this.OnCodeIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeValue1", DbType="VarChar(50)")]
		public string CodeValue1
		{
			get
			{
				return this._CodeValue1;
			}
			set
			{
				if ((this._CodeValue1 != value))
				{
					this.OnCodeValue1Changing(value);
					this.SendPropertyChanging();
					this._CodeValue1 = value;
					this.SendPropertyChanged("CodeValue1");
					this.OnCodeValue1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeValue2", DbType="VarChar(50)")]
		public string CodeValue2
		{
			get
			{
				return this._CodeValue2;
			}
			set
			{
				if ((this._CodeValue2 != value))
				{
					this.OnCodeValue2Changing(value);
					this.SendPropertyChanging();
					this._CodeValue2 = value;
					this.SendPropertyChanged("CodeValue2");
					this.OnCodeValue2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeValue3", DbType="VarChar(50)")]
		public string CodeValue3
		{
			get
			{
				return this._CodeValue3;
			}
			set
			{
				if ((this._CodeValue3 != value))
				{
					this.OnCodeValue3Changing(value);
					this.SendPropertyChanging();
					this._CodeValue3 = value;
					this.SendPropertyChanged("CodeValue3");
					this.OnCodeValue3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMark", DbType="VarChar(1000)")]
		public string CodeMark
		{
			get
			{
				return this._CodeMark;
			}
			set
			{
				if ((this._CodeMark != value))
				{
					this.OnCodeMarkChanging(value);
					this.SendPropertyChanging();
					this._CodeMark = value;
					this.SendPropertyChanged("CodeMark");
					this.OnCodeMarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
