#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.WebClient.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iwayward")]
	public partial class smgInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertsmgInfo(smgInfo instance);
    partial void UpdatesmgInfo(smgInfo instance);
    partial void DeletesmgInfo(smgInfo instance);
    #endregion
		
		public smgInfoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iwaywardConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public smgInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public smgInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public smgInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public smgInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<smgInfo> smgInfo
		{
			get
			{
				return this.GetTable<smgInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smgInfo")]
	public partial class smgInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _smgID;
		
		private string _FromUserID;
		
		private string _ToUserID;
		
		private string _smgtype;
		
		private string _smgContext;
		
		private string _smgimg;
		
		private string _smgvioe;
		
		private string _fromTime;
		
		private string _toTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsmgIDChanging(int value);
    partial void OnsmgIDChanged();
    partial void OnFromUserIDChanging(string value);
    partial void OnFromUserIDChanged();
    partial void OnToUserIDChanging(string value);
    partial void OnToUserIDChanged();
    partial void OnsmgtypeChanging(string value);
    partial void OnsmgtypeChanged();
    partial void OnsmgContextChanging(string value);
    partial void OnsmgContextChanged();
    partial void OnsmgimgChanging(string value);
    partial void OnsmgimgChanged();
    partial void OnsmgvioeChanging(string value);
    partial void OnsmgvioeChanged();
    partial void OnfromTimeChanging(string value);
    partial void OnfromTimeChanged();
    partial void OntoTimeChanging(string value);
    partial void OntoTimeChanged();
    #endregion
		
		public smgInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int smgID
		{
			get
			{
				return this._smgID;
			}
			set
			{
				if ((this._smgID != value))
				{
					this.OnsmgIDChanging(value);
					this.SendPropertyChanging();
					this._smgID = value;
					this.SendPropertyChanged("smgID");
					this.OnsmgIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromUserID", DbType="NVarChar(50)")]
		public string FromUserID
		{
			get
			{
				return this._FromUserID;
			}
			set
			{
				if ((this._FromUserID != value))
				{
					this.OnFromUserIDChanging(value);
					this.SendPropertyChanging();
					this._FromUserID = value;
					this.SendPropertyChanged("FromUserID");
					this.OnFromUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToUserID", DbType="NVarChar(50)")]
		public string ToUserID
		{
			get
			{
				return this._ToUserID;
			}
			set
			{
				if ((this._ToUserID != value))
				{
					this.OnToUserIDChanging(value);
					this.SendPropertyChanging();
					this._ToUserID = value;
					this.SendPropertyChanged("ToUserID");
					this.OnToUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgtype", DbType="VarChar(32)")]
		public string smgtype
		{
			get
			{
				return this._smgtype;
			}
			set
			{
				if ((this._smgtype != value))
				{
					this.OnsmgtypeChanging(value);
					this.SendPropertyChanging();
					this._smgtype = value;
					this.SendPropertyChanged("smgtype");
					this.OnsmgtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgContext", DbType="VarChar(MAX)")]
		public string smgContext
		{
			get
			{
				return this._smgContext;
			}
			set
			{
				if ((this._smgContext != value))
				{
					this.OnsmgContextChanging(value);
					this.SendPropertyChanging();
					this._smgContext = value;
					this.SendPropertyChanged("smgContext");
					this.OnsmgContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgimg", DbType="VarChar(MAX)")]
		public string smgimg
		{
			get
			{
				return this._smgimg;
			}
			set
			{
				if ((this._smgimg != value))
				{
					this.OnsmgimgChanging(value);
					this.SendPropertyChanging();
					this._smgimg = value;
					this.SendPropertyChanged("smgimg");
					this.OnsmgimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgvioe", DbType="VarChar(MAX)")]
		public string smgvioe
		{
			get
			{
				return this._smgvioe;
			}
			set
			{
				if ((this._smgvioe != value))
				{
					this.OnsmgvioeChanging(value);
					this.SendPropertyChanging();
					this._smgvioe = value;
					this.SendPropertyChanged("smgvioe");
					this.OnsmgvioeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fromTime", DbType="NVarChar(50)")]
		public string fromTime
		{
			get
			{
				return this._fromTime;
			}
			set
			{
				if ((this._fromTime != value))
				{
					this.OnfromTimeChanging(value);
					this.SendPropertyChanging();
					this._fromTime = value;
					this.SendPropertyChanged("fromTime");
					this.OnfromTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toTime", DbType="NVarChar(50)")]
		public string toTime
		{
			get
			{
				return this._toTime;
			}
			set
			{
				if ((this._toTime != value))
				{
					this.OntoTimeChanging(value);
					this.SendPropertyChanging();
					this._toTime = value;
					this.SendPropertyChanged("toTime");
					this.OntoTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
