#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.WebClient.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iwayward")]
	public partial class userInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUserInfo(UserInfo instance);
    partial void UpdateUserInfo(UserInfo instance);
    partial void DeleteUserInfo(UserInfo instance);
    #endregion
		
		public userInfoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iwaywardConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public userInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public userInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public userInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public userInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserInfo> UserInfo
		{
			get
			{
				return this.GetTable<UserInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInfo")]
	public partial class UserInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userID;
		
		private string _phone;
		
		private string _headUrl;
		
		private string _nickName;
		
		private string _userName;
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _sex;
		
		private string _region;
		
		private string _city;
		
		private string _province;
		
		private string _mail;
		
		private System.Nullable<int> _qqNo;
		
		private string _sinaID;
		
		private string _tengID;
		
		private string _baiduID;
		
		private string _weixinID;
		
		private string _weixinName;
		
		private string _weixinTwo;
		
		private string _professional;
		
		private string _industry;
		
		private string _position;
		
		private string _erweima;
		
		private string _zhuceTime;
		
		private string _qianming;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnheadUrlChanging(string value);
    partial void OnheadUrlChanged();
    partial void OnnickNameChanging(string value);
    partial void OnnickNameChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OnsexChanging(System.Nullable<int> value);
    partial void OnsexChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OnqqNoChanging(System.Nullable<int> value);
    partial void OnqqNoChanged();
    partial void OnsinaIDChanging(string value);
    partial void OnsinaIDChanged();
    partial void OntengIDChanging(string value);
    partial void OntengIDChanged();
    partial void OnbaiduIDChanging(string value);
    partial void OnbaiduIDChanged();
    partial void OnweixinIDChanging(string value);
    partial void OnweixinIDChanged();
    partial void OnweixinNameChanging(string value);
    partial void OnweixinNameChanged();
    partial void OnweixinTwoChanging(string value);
    partial void OnweixinTwoChanged();
    partial void OnprofessionalChanging(string value);
    partial void OnprofessionalChanged();
    partial void OnindustryChanging(string value);
    partial void OnindustryChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnerweimaChanging(string value);
    partial void OnerweimaChanged();
    partial void OnzhuceTimeChanging(string value);
    partial void OnzhuceTimeChanged();
    partial void OnqianmingChanging(string value);
    partial void OnqianmingChanged();
    #endregion
		
		public UserInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headUrl", DbType="VarChar(100)")]
		public string headUrl
		{
			get
			{
				return this._headUrl;
			}
			set
			{
				if ((this._headUrl != value))
				{
					this.OnheadUrlChanging(value);
					this.SendPropertyChanging();
					this._headUrl = value;
					this.SendPropertyChanged("headUrl");
					this.OnheadUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickName", DbType="VarChar(50)")]
		public string nickName
		{
			get
			{
				return this._nickName;
			}
			set
			{
				if ((this._nickName != value))
				{
					this.OnnickNameChanging(value);
					this.SendPropertyChanging();
					this._nickName = value;
					this.SendPropertyChanged("nickName");
					this.OnnickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="Int")]
		public System.Nullable<int> sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(100)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(100)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(100)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qqNo", DbType="Int")]
		public System.Nullable<int> qqNo
		{
			get
			{
				return this._qqNo;
			}
			set
			{
				if ((this._qqNo != value))
				{
					this.OnqqNoChanging(value);
					this.SendPropertyChanging();
					this._qqNo = value;
					this.SendPropertyChanged("qqNo");
					this.OnqqNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinaID", DbType="VarChar(50)")]
		public string sinaID
		{
			get
			{
				return this._sinaID;
			}
			set
			{
				if ((this._sinaID != value))
				{
					this.OnsinaIDChanging(value);
					this.SendPropertyChanging();
					this._sinaID = value;
					this.SendPropertyChanged("sinaID");
					this.OnsinaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tengID", DbType="VarChar(50)")]
		public string tengID
		{
			get
			{
				return this._tengID;
			}
			set
			{
				if ((this._tengID != value))
				{
					this.OntengIDChanging(value);
					this.SendPropertyChanging();
					this._tengID = value;
					this.SendPropertyChanged("tengID");
					this.OntengIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baiduID", DbType="VarChar(50)")]
		public string baiduID
		{
			get
			{
				return this._baiduID;
			}
			set
			{
				if ((this._baiduID != value))
				{
					this.OnbaiduIDChanging(value);
					this.SendPropertyChanging();
					this._baiduID = value;
					this.SendPropertyChanged("baiduID");
					this.OnbaiduIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weixinID", DbType="VarChar(50)")]
		public string weixinID
		{
			get
			{
				return this._weixinID;
			}
			set
			{
				if ((this._weixinID != value))
				{
					this.OnweixinIDChanging(value);
					this.SendPropertyChanging();
					this._weixinID = value;
					this.SendPropertyChanged("weixinID");
					this.OnweixinIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weixinName", DbType="VarChar(100)")]
		public string weixinName
		{
			get
			{
				return this._weixinName;
			}
			set
			{
				if ((this._weixinName != value))
				{
					this.OnweixinNameChanging(value);
					this.SendPropertyChanging();
					this._weixinName = value;
					this.SendPropertyChanged("weixinName");
					this.OnweixinNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weixinTwo", DbType="VarChar(100)")]
		public string weixinTwo
		{
			get
			{
				return this._weixinTwo;
			}
			set
			{
				if ((this._weixinTwo != value))
				{
					this.OnweixinTwoChanging(value);
					this.SendPropertyChanging();
					this._weixinTwo = value;
					this.SendPropertyChanged("weixinTwo");
					this.OnweixinTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_professional", DbType="VarChar(100)")]
		public string professional
		{
			get
			{
				return this._professional;
			}
			set
			{
				if ((this._professional != value))
				{
					this.OnprofessionalChanging(value);
					this.SendPropertyChanging();
					this._professional = value;
					this.SendPropertyChanged("professional");
					this.OnprofessionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_industry", DbType="VarChar(100)")]
		public string industry
		{
			get
			{
				return this._industry;
			}
			set
			{
				if ((this._industry != value))
				{
					this.OnindustryChanging(value);
					this.SendPropertyChanging();
					this._industry = value;
					this.SendPropertyChanged("industry");
					this.OnindustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(100)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_erweima", DbType="VarChar(100)")]
		public string erweima
		{
			get
			{
				return this._erweima;
			}
			set
			{
				if ((this._erweima != value))
				{
					this.OnerweimaChanging(value);
					this.SendPropertyChanging();
					this._erweima = value;
					this.SendPropertyChanged("erweima");
					this.OnerweimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhuceTime", DbType="NVarChar(50)")]
		public string zhuceTime
		{
			get
			{
				return this._zhuceTime;
			}
			set
			{
				if ((this._zhuceTime != value))
				{
					this.OnzhuceTimeChanging(value);
					this.SendPropertyChanging();
					this._zhuceTime = value;
					this.SendPropertyChanged("zhuceTime");
					this.OnzhuceTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qianming", DbType="VarChar(500)")]
		public string qianming
		{
			get
			{
				return this._qianming;
			}
			set
			{
				if ((this._qianming != value))
				{
					this.OnqianmingChanging(value);
					this.SendPropertyChanging();
					this._qianming = value;
					this.SendPropertyChanged("qianming");
					this.OnqianmingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
