#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.WebServices.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iwayward")]
	public partial class iwaywardDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCODE(CODE instance);
    partial void UpdateCODE(CODE instance);
    partial void DeleteCODE(CODE instance);
    partial void Insertindustry(industry instance);
    partial void Updateindustry(industry instance);
    partial void Deleteindustry(industry instance);
    partial void Insertcomments(comments instance);
    partial void Updatecomments(comments instance);
    partial void Deletecomments(comments instance);
    partial void InsertServiceInformation(ServiceInformation instance);
    partial void UpdateServiceInformation(ServiceInformation instance);
    partial void DeleteServiceInformation(ServiceInformation instance);
    partial void InsertUserInfo(UserInfo instance);
    partial void UpdateUserInfo(UserInfo instance);
    partial void DeleteUserInfo(UserInfo instance);
    partial void InsertsmgInfo(smgInfo instance);
    partial void UpdatesmgInfo(smgInfo instance);
    partial void DeletesmgInfo(smgInfo instance);
    #endregion
		
		public iwaywardDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iwaywardConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public iwaywardDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iwaywardDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iwaywardDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iwaywardDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CODE> CODE
		{
			get
			{
				return this.GetTable<CODE>();
			}
		}
		
		public System.Data.Linq.Table<industry> industry
		{
			get
			{
				return this.GetTable<industry>();
			}
		}
		
		public System.Data.Linq.Table<AttentionIndustry> AttentionIndustry
		{
			get
			{
				return this.GetTable<AttentionIndustry>();
			}
		}
		
		public System.Data.Linq.Table<comments> comments
		{
			get
			{
				return this.GetTable<comments>();
			}
		}
		
		public System.Data.Linq.Table<PersonnelRelationship> PersonnelRelationship
		{
			get
			{
				return this.GetTable<PersonnelRelationship>();
			}
		}
		
		public System.Data.Linq.Table<ServiceInformation> ServiceInformation
		{
			get
			{
				return this.GetTable<ServiceInformation>();
			}
		}
		
		public System.Data.Linq.Table<servicepipei> servicepipei
		{
			get
			{
				return this.GetTable<servicepipei>();
			}
		}
		
		public System.Data.Linq.Table<UserInfo> UserInfo
		{
			get
			{
				return this.GetTable<UserInfo>();
			}
		}
		
		public System.Data.Linq.Table<smgInfo> smgInfo
		{
			get
			{
				return this.GetTable<smgInfo>();
			}
		}
		
		public System.Data.Linq.Table<companyTable> companyTable
		{
			get
			{
				return this.GetTable<companyTable>();
			}
		}
		
		public System.Data.Linq.Table<jobTable> jobTable
		{
			get
			{
				return this.GetTable<jobTable>();
			}
		}
		
		public System.Data.Linq.Table<positionInfo> positionInfo
		{
			get
			{
				return this.GetTable<positionInfo>();
			}
		}
		
		public System.Data.Linq.Table<projectTable> projectTable
		{
			get
			{
				return this.GetTable<projectTable>();
			}
		}
		
		public System.Data.Linq.Table<regionTable> regionTable
		{
			get
			{
				return this.GetTable<regionTable>();
			}
		}
		
		public System.Data.Linq.Table<resume> resume
		{
			get
			{
				return this.GetTable<resume>();
			}
		}
		
		public System.Data.Linq.Table<resumeJob> resumeJob
		{
			get
			{
				return this.GetTable<resumeJob>();
			}
		}
		
		public System.Data.Linq.Table<resumePoject> resumePoject
		{
			get
			{
				return this.GetTable<resumePoject>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CODE")]
	public partial class CODE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeID;
		
		private string _CodeName;
		
		private string _CodeFatherID;
		
		private System.Nullable<int> _CodeIndex;
		
		private string _CodeValue1;
		
		private string _CodeValue2;
		
		private string _CodeValue3;
		
		private string _CodeMark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeIDChanging(string value);
    partial void OnCodeIDChanged();
    partial void OnCodeNameChanging(string value);
    partial void OnCodeNameChanged();
    partial void OnCodeFatherIDChanging(string value);
    partial void OnCodeFatherIDChanged();
    partial void OnCodeIndexChanging(System.Nullable<int> value);
    partial void OnCodeIndexChanged();
    partial void OnCodeValue1Changing(string value);
    partial void OnCodeValue1Changed();
    partial void OnCodeValue2Changing(string value);
    partial void OnCodeValue2Changed();
    partial void OnCodeValue3Changing(string value);
    partial void OnCodeValue3Changed();
    partial void OnCodeMarkChanging(string value);
    partial void OnCodeMarkChanged();
    #endregion
		
		public CODE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeID", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeID
		{
			get
			{
				return this._CodeID;
			}
			set
			{
				if ((this._CodeID != value))
				{
					this.OnCodeIDChanging(value);
					this.SendPropertyChanging();
					this._CodeID = value;
					this.SendPropertyChanged("CodeID");
					this.OnCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeName", DbType="VarChar(100)")]
		public string CodeName
		{
			get
			{
				return this._CodeName;
			}
			set
			{
				if ((this._CodeName != value))
				{
					this.OnCodeNameChanging(value);
					this.SendPropertyChanging();
					this._CodeName = value;
					this.SendPropertyChanged("CodeName");
					this.OnCodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeFatherID", DbType="VarChar(32)")]
		public string CodeFatherID
		{
			get
			{
				return this._CodeFatherID;
			}
			set
			{
				if ((this._CodeFatherID != value))
				{
					this.OnCodeFatherIDChanging(value);
					this.SendPropertyChanging();
					this._CodeFatherID = value;
					this.SendPropertyChanged("CodeFatherID");
					this.OnCodeFatherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeIndex", DbType="Int")]
		public System.Nullable<int> CodeIndex
		{
			get
			{
				return this._CodeIndex;
			}
			set
			{
				if ((this._CodeIndex != value))
				{
					this.OnCodeIndexChanging(value);
					this.SendPropertyChanging();
					this._CodeIndex = value;
					this.SendPropertyChanged("CodeIndex");
					this.OnCodeIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeValue1", DbType="VarChar(50)")]
		public string CodeValue1
		{
			get
			{
				return this._CodeValue1;
			}
			set
			{
				if ((this._CodeValue1 != value))
				{
					this.OnCodeValue1Changing(value);
					this.SendPropertyChanging();
					this._CodeValue1 = value;
					this.SendPropertyChanged("CodeValue1");
					this.OnCodeValue1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeValue2", DbType="VarChar(50)")]
		public string CodeValue2
		{
			get
			{
				return this._CodeValue2;
			}
			set
			{
				if ((this._CodeValue2 != value))
				{
					this.OnCodeValue2Changing(value);
					this.SendPropertyChanging();
					this._CodeValue2 = value;
					this.SendPropertyChanged("CodeValue2");
					this.OnCodeValue2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeValue3", DbType="VarChar(50)")]
		public string CodeValue3
		{
			get
			{
				return this._CodeValue3;
			}
			set
			{
				if ((this._CodeValue3 != value))
				{
					this.OnCodeValue3Changing(value);
					this.SendPropertyChanging();
					this._CodeValue3 = value;
					this.SendPropertyChanged("CodeValue3");
					this.OnCodeValue3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMark", DbType="VarChar(1000)")]
		public string CodeMark
		{
			get
			{
				return this._CodeMark;
			}
			set
			{
				if ((this._CodeMark != value))
				{
					this.OnCodeMarkChanging(value);
					this.SendPropertyChanging();
					this._CodeMark = value;
					this.SendPropertyChanged("CodeMark");
					this.OnCodeMarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.industry")]
	public partial class industry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IndID;
		
		private string _IndName;
		
		private System.Nullable<int> _IndChildID;
		
		private string _IndChildName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIndIDChanging(int value);
    partial void OnIndIDChanged();
    partial void OnIndNameChanging(string value);
    partial void OnIndNameChanged();
    partial void OnIndChildIDChanging(System.Nullable<int> value);
    partial void OnIndChildIDChanged();
    partial void OnIndChildNameChanging(string value);
    partial void OnIndChildNameChanged();
    #endregion
		
		public industry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IndID
		{
			get
			{
				return this._IndID;
			}
			set
			{
				if ((this._IndID != value))
				{
					this.OnIndIDChanging(value);
					this.SendPropertyChanging();
					this._IndID = value;
					this.SendPropertyChanged("IndID");
					this.OnIndIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndName", DbType="VarChar(50)")]
		public string IndName
		{
			get
			{
				return this._IndName;
			}
			set
			{
				if ((this._IndName != value))
				{
					this.OnIndNameChanging(value);
					this.SendPropertyChanging();
					this._IndName = value;
					this.SendPropertyChanged("IndName");
					this.OnIndNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndChildID", DbType="Int")]
		public System.Nullable<int> IndChildID
		{
			get
			{
				return this._IndChildID;
			}
			set
			{
				if ((this._IndChildID != value))
				{
					this.OnIndChildIDChanging(value);
					this.SendPropertyChanging();
					this._IndChildID = value;
					this.SendPropertyChanged("IndChildID");
					this.OnIndChildIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndChildName", DbType="VarChar(50)")]
		public string IndChildName
		{
			get
			{
				return this._IndChildName;
			}
			set
			{
				if ((this._IndChildName != value))
				{
					this.OnIndChildNameChanging(value);
					this.SendPropertyChanging();
					this._IndChildName = value;
					this.SendPropertyChanged("IndChildName");
					this.OnIndChildNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AttentionIndustry")]
	public partial class AttentionIndustry
	{
		
		private string _UserID;
		
		private System.Nullable<int> _IndID1;
		
		private string _IndMark1;
		
		private System.Nullable<int> _IndID2;
		
		private string _IndMark2;
		
		private System.Nullable<int> _IndID3;
		
		private string _IndMark3;
		
		public AttentionIndustry()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndID1", DbType="Int")]
		public System.Nullable<int> IndID1
		{
			get
			{
				return this._IndID1;
			}
			set
			{
				if ((this._IndID1 != value))
				{
					this._IndID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndMark1", DbType="VarChar(MAX)")]
		public string IndMark1
		{
			get
			{
				return this._IndMark1;
			}
			set
			{
				if ((this._IndMark1 != value))
				{
					this._IndMark1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndID2", DbType="Int")]
		public System.Nullable<int> IndID2
		{
			get
			{
				return this._IndID2;
			}
			set
			{
				if ((this._IndID2 != value))
				{
					this._IndID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndMark2", DbType="VarChar(MAX)")]
		public string IndMark2
		{
			get
			{
				return this._IndMark2;
			}
			set
			{
				if ((this._IndMark2 != value))
				{
					this._IndMark2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndID3", DbType="Int")]
		public System.Nullable<int> IndID3
		{
			get
			{
				return this._IndID3;
			}
			set
			{
				if ((this._IndID3 != value))
				{
					this._IndID3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndMark3", DbType="VarChar(MAX)")]
		public string IndMark3
		{
			get
			{
				return this._IndMark3;
			}
			set
			{
				if ((this._IndMark3 != value))
				{
					this._IndMark3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.comments")]
	public partial class comments : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _commID;
		
		private System.Nullable<int> _serviceID;
		
		private string _context;
		
		private string _commDateTime;
		
		private System.Nullable<int> _UserID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncommIDChanging(int value);
    partial void OncommIDChanged();
    partial void OnserviceIDChanging(System.Nullable<int> value);
    partial void OnserviceIDChanged();
    partial void OncontextChanging(string value);
    partial void OncontextChanged();
    partial void OncommDateTimeChanging(string value);
    partial void OncommDateTimeChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public comments()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int commID
		{
			get
			{
				return this._commID;
			}
			set
			{
				if ((this._commID != value))
				{
					this.OncommIDChanging(value);
					this.SendPropertyChanging();
					this._commID = value;
					this.SendPropertyChanged("commID");
					this.OncommIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceID", DbType="Int")]
		public System.Nullable<int> serviceID
		{
			get
			{
				return this._serviceID;
			}
			set
			{
				if ((this._serviceID != value))
				{
					this.OnserviceIDChanging(value);
					this.SendPropertyChanging();
					this._serviceID = value;
					this.SendPropertyChanged("serviceID");
					this.OnserviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_context", DbType="VarChar(MAX)")]
		public string context
		{
			get
			{
				return this._context;
			}
			set
			{
				if ((this._context != value))
				{
					this.OncontextChanging(value);
					this.SendPropertyChanging();
					this._context = value;
					this.SendPropertyChanged("context");
					this.OncontextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commDateTime", DbType="NVarChar(50)")]
		public string commDateTime
		{
			get
			{
				return this._commDateTime;
			}
			set
			{
				if ((this._commDateTime != value))
				{
					this.OncommDateTimeChanging(value);
					this.SendPropertyChanging();
					this._commDateTime = value;
					this.SendPropertyChanged("commDateTime");
					this.OncommDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonnelRelationship")]
	public partial class PersonnelRelationship
	{
		
		private string _UserID;
		
		private string _objType;
		
		private string _GUserID;
		
		private System.Nullable<int> _IndID;
		
		public PersonnelRelationship()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objType", DbType="VarChar(32)")]
		public string objType
		{
			get
			{
				return this._objType;
			}
			set
			{
				if ((this._objType != value))
				{
					this._objType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUserID", DbType="NVarChar(50)")]
		public string GUserID
		{
			get
			{
				return this._GUserID;
			}
			set
			{
				if ((this._GUserID != value))
				{
					this._GUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndID", DbType="Int")]
		public System.Nullable<int> IndID
		{
			get
			{
				return this._IndID;
			}
			set
			{
				if ((this._IndID != value))
				{
					this._IndID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServiceInformation")]
	public partial class ServiceInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ServicID;
		
		private string _UserID;
		
		private string _title;
		
		private string _serviceTyoe;
		
		private System.Nullable<int> _IndID;
		
		private string _sendTime;
		
		private string _region;
		
		private string _city;
		
		private string _province;
		
		private string _macrk;
		
		private System.Nullable<decimal> _longitude;
		
		private System.Nullable<decimal> _latitude;
		
		private string _address;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnServicIDChanging(int value);
    partial void OnServicIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnserviceTyoeChanging(string value);
    partial void OnserviceTyoeChanged();
    partial void OnIndIDChanging(System.Nullable<int> value);
    partial void OnIndIDChanged();
    partial void OnsendTimeChanging(string value);
    partial void OnsendTimeChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnmacrkChanging(string value);
    partial void OnmacrkChanged();
    partial void OnlongitudeChanging(System.Nullable<decimal> value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(System.Nullable<decimal> value);
    partial void OnlatitudeChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public ServiceInformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServicID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ServicID
		{
			get
			{
				return this._ServicID;
			}
			set
			{
				if ((this._ServicID != value))
				{
					this.OnServicIDChanging(value);
					this.SendPropertyChanging();
					this._ServicID = value;
					this.SendPropertyChanged("ServicID");
					this.OnServicIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(32)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceTyoe", DbType="VarChar(32)")]
		public string serviceTyoe
		{
			get
			{
				return this._serviceTyoe;
			}
			set
			{
				if ((this._serviceTyoe != value))
				{
					this.OnserviceTyoeChanging(value);
					this.SendPropertyChanging();
					this._serviceTyoe = value;
					this.SendPropertyChanged("serviceTyoe");
					this.OnserviceTyoeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndID", DbType="Int")]
		public System.Nullable<int> IndID
		{
			get
			{
				return this._IndID;
			}
			set
			{
				if ((this._IndID != value))
				{
					this.OnIndIDChanging(value);
					this.SendPropertyChanging();
					this._IndID = value;
					this.SendPropertyChanged("IndID");
					this.OnIndIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendTime", DbType="NVarChar(50)")]
		public string sendTime
		{
			get
			{
				return this._sendTime;
			}
			set
			{
				if ((this._sendTime != value))
				{
					this.OnsendTimeChanging(value);
					this.SendPropertyChanging();
					this._sendTime = value;
					this.SendPropertyChanged("sendTime");
					this.OnsendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(100)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(100)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macrk", DbType="VarChar(100)")]
		public string macrk
		{
			get
			{
				return this._macrk;
			}
			set
			{
				if ((this._macrk != value))
				{
					this.OnmacrkChanging(value);
					this.SendPropertyChanging();
					this._macrk = value;
					this.SendPropertyChanged("macrk");
					this.OnmacrkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(32,32)")]
		public System.Nullable<decimal> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(32,32)")]
		public System.Nullable<decimal> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.servicepipei")]
	public partial class servicepipei
	{
		
		private string _UserID;
		
		private System.Nullable<int> _ServicID;
		
		private string _PUserID;
		
		public servicepipei()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServicID", DbType="Int")]
		public System.Nullable<int> ServicID
		{
			get
			{
				return this._ServicID;
			}
			set
			{
				if ((this._ServicID != value))
				{
					this._ServicID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUserID", DbType="NVarChar(50)")]
		public string PUserID
		{
			get
			{
				return this._PUserID;
			}
			set
			{
				if ((this._PUserID != value))
				{
					this._PUserID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInfo")]
	public partial class UserInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userID;
		
		private string _phone;
		
		private string _headUrl;
		
		private string _nickName;
		
		private string _userName;
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _sex;
		
		private string _region;
		
		private string _city;
		
		private string _province;
		
		private string _mail;
		
		private System.Nullable<int> _qqNo;
		
		private string _sinaID;
		
		private string _tengID;
		
		private string _baiduID;
		
		private string _weixinID;
		
		private string _weixinName;
		
		private string _weixinTwo;
		
		private string _professional;
		
		private string _industry;
		
		private string _position;
		
		private string _erweima;
		
		private string _zhuceTime;
		
		private string _qianming;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnheadUrlChanging(string value);
    partial void OnheadUrlChanged();
    partial void OnnickNameChanging(string value);
    partial void OnnickNameChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OnsexChanging(System.Nullable<int> value);
    partial void OnsexChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OnqqNoChanging(System.Nullable<int> value);
    partial void OnqqNoChanged();
    partial void OnsinaIDChanging(string value);
    partial void OnsinaIDChanged();
    partial void OntengIDChanging(string value);
    partial void OntengIDChanged();
    partial void OnbaiduIDChanging(string value);
    partial void OnbaiduIDChanged();
    partial void OnweixinIDChanging(string value);
    partial void OnweixinIDChanged();
    partial void OnweixinNameChanging(string value);
    partial void OnweixinNameChanged();
    partial void OnweixinTwoChanging(string value);
    partial void OnweixinTwoChanged();
    partial void OnprofessionalChanging(string value);
    partial void OnprofessionalChanged();
    partial void OnindustryChanging(string value);
    partial void OnindustryChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnerweimaChanging(string value);
    partial void OnerweimaChanged();
    partial void OnzhuceTimeChanging(string value);
    partial void OnzhuceTimeChanged();
    partial void OnqianmingChanging(string value);
    partial void OnqianmingChanged();
    #endregion
		
		public UserInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headUrl", DbType="VarChar(100)")]
		public string headUrl
		{
			get
			{
				return this._headUrl;
			}
			set
			{
				if ((this._headUrl != value))
				{
					this.OnheadUrlChanging(value);
					this.SendPropertyChanging();
					this._headUrl = value;
					this.SendPropertyChanged("headUrl");
					this.OnheadUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickName", DbType="VarChar(50)")]
		public string nickName
		{
			get
			{
				return this._nickName;
			}
			set
			{
				if ((this._nickName != value))
				{
					this.OnnickNameChanging(value);
					this.SendPropertyChanging();
					this._nickName = value;
					this.SendPropertyChanged("nickName");
					this.OnnickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="Int")]
		public System.Nullable<int> sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(100)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(100)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(100)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qqNo", DbType="Int")]
		public System.Nullable<int> qqNo
		{
			get
			{
				return this._qqNo;
			}
			set
			{
				if ((this._qqNo != value))
				{
					this.OnqqNoChanging(value);
					this.SendPropertyChanging();
					this._qqNo = value;
					this.SendPropertyChanged("qqNo");
					this.OnqqNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinaID", DbType="VarChar(50)")]
		public string sinaID
		{
			get
			{
				return this._sinaID;
			}
			set
			{
				if ((this._sinaID != value))
				{
					this.OnsinaIDChanging(value);
					this.SendPropertyChanging();
					this._sinaID = value;
					this.SendPropertyChanged("sinaID");
					this.OnsinaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tengID", DbType="VarChar(50)")]
		public string tengID
		{
			get
			{
				return this._tengID;
			}
			set
			{
				if ((this._tengID != value))
				{
					this.OntengIDChanging(value);
					this.SendPropertyChanging();
					this._tengID = value;
					this.SendPropertyChanged("tengID");
					this.OntengIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baiduID", DbType="VarChar(50)")]
		public string baiduID
		{
			get
			{
				return this._baiduID;
			}
			set
			{
				if ((this._baiduID != value))
				{
					this.OnbaiduIDChanging(value);
					this.SendPropertyChanging();
					this._baiduID = value;
					this.SendPropertyChanged("baiduID");
					this.OnbaiduIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weixinID", DbType="VarChar(50)")]
		public string weixinID
		{
			get
			{
				return this._weixinID;
			}
			set
			{
				if ((this._weixinID != value))
				{
					this.OnweixinIDChanging(value);
					this.SendPropertyChanging();
					this._weixinID = value;
					this.SendPropertyChanged("weixinID");
					this.OnweixinIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weixinName", DbType="VarChar(100)")]
		public string weixinName
		{
			get
			{
				return this._weixinName;
			}
			set
			{
				if ((this._weixinName != value))
				{
					this.OnweixinNameChanging(value);
					this.SendPropertyChanging();
					this._weixinName = value;
					this.SendPropertyChanged("weixinName");
					this.OnweixinNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weixinTwo", DbType="VarChar(100)")]
		public string weixinTwo
		{
			get
			{
				return this._weixinTwo;
			}
			set
			{
				if ((this._weixinTwo != value))
				{
					this.OnweixinTwoChanging(value);
					this.SendPropertyChanging();
					this._weixinTwo = value;
					this.SendPropertyChanged("weixinTwo");
					this.OnweixinTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_professional", DbType="VarChar(100)")]
		public string professional
		{
			get
			{
				return this._professional;
			}
			set
			{
				if ((this._professional != value))
				{
					this.OnprofessionalChanging(value);
					this.SendPropertyChanging();
					this._professional = value;
					this.SendPropertyChanged("professional");
					this.OnprofessionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_industry", DbType="VarChar(100)")]
		public string industry
		{
			get
			{
				return this._industry;
			}
			set
			{
				if ((this._industry != value))
				{
					this.OnindustryChanging(value);
					this.SendPropertyChanging();
					this._industry = value;
					this.SendPropertyChanged("industry");
					this.OnindustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(100)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_erweima", DbType="VarChar(100)")]
		public string erweima
		{
			get
			{
				return this._erweima;
			}
			set
			{
				if ((this._erweima != value))
				{
					this.OnerweimaChanging(value);
					this.SendPropertyChanging();
					this._erweima = value;
					this.SendPropertyChanged("erweima");
					this.OnerweimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhuceTime", DbType="NVarChar(50)")]
		public string zhuceTime
		{
			get
			{
				return this._zhuceTime;
			}
			set
			{
				if ((this._zhuceTime != value))
				{
					this.OnzhuceTimeChanging(value);
					this.SendPropertyChanging();
					this._zhuceTime = value;
					this.SendPropertyChanged("zhuceTime");
					this.OnzhuceTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qianming", DbType="VarChar(500)")]
		public string qianming
		{
			get
			{
				return this._qianming;
			}
			set
			{
				if ((this._qianming != value))
				{
					this.OnqianmingChanging(value);
					this.SendPropertyChanging();
					this._qianming = value;
					this.SendPropertyChanged("qianming");
					this.OnqianmingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smgInfo")]
	public partial class smgInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _smgID;
		
		private string _FromUserID;
		
		private string _ToUserID;
		
		private string _smgtype;
		
		private string _smgContext;
		
		private string _smgimg;
		
		private string _smgvioe;
		
		private string _fromTime;
		
		private string _toTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsmgIDChanging(int value);
    partial void OnsmgIDChanged();
    partial void OnFromUserIDChanging(string value);
    partial void OnFromUserIDChanged();
    partial void OnToUserIDChanging(string value);
    partial void OnToUserIDChanged();
    partial void OnsmgtypeChanging(string value);
    partial void OnsmgtypeChanged();
    partial void OnsmgContextChanging(string value);
    partial void OnsmgContextChanged();
    partial void OnsmgimgChanging(string value);
    partial void OnsmgimgChanged();
    partial void OnsmgvioeChanging(string value);
    partial void OnsmgvioeChanged();
    partial void OnfromTimeChanging(string value);
    partial void OnfromTimeChanged();
    partial void OntoTimeChanging(string value);
    partial void OntoTimeChanged();
    #endregion
		
		public smgInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int smgID
		{
			get
			{
				return this._smgID;
			}
			set
			{
				if ((this._smgID != value))
				{
					this.OnsmgIDChanging(value);
					this.SendPropertyChanging();
					this._smgID = value;
					this.SendPropertyChanged("smgID");
					this.OnsmgIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromUserID", DbType="NVarChar(50)")]
		public string FromUserID
		{
			get
			{
				return this._FromUserID;
			}
			set
			{
				if ((this._FromUserID != value))
				{
					this.OnFromUserIDChanging(value);
					this.SendPropertyChanging();
					this._FromUserID = value;
					this.SendPropertyChanged("FromUserID");
					this.OnFromUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToUserID", DbType="NVarChar(50)")]
		public string ToUserID
		{
			get
			{
				return this._ToUserID;
			}
			set
			{
				if ((this._ToUserID != value))
				{
					this.OnToUserIDChanging(value);
					this.SendPropertyChanging();
					this._ToUserID = value;
					this.SendPropertyChanged("ToUserID");
					this.OnToUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgtype", DbType="VarChar(32)")]
		public string smgtype
		{
			get
			{
				return this._smgtype;
			}
			set
			{
				if ((this._smgtype != value))
				{
					this.OnsmgtypeChanging(value);
					this.SendPropertyChanging();
					this._smgtype = value;
					this.SendPropertyChanged("smgtype");
					this.OnsmgtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgContext", DbType="VarChar(MAX)")]
		public string smgContext
		{
			get
			{
				return this._smgContext;
			}
			set
			{
				if ((this._smgContext != value))
				{
					this.OnsmgContextChanging(value);
					this.SendPropertyChanging();
					this._smgContext = value;
					this.SendPropertyChanged("smgContext");
					this.OnsmgContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgimg", DbType="VarChar(MAX)")]
		public string smgimg
		{
			get
			{
				return this._smgimg;
			}
			set
			{
				if ((this._smgimg != value))
				{
					this.OnsmgimgChanging(value);
					this.SendPropertyChanging();
					this._smgimg = value;
					this.SendPropertyChanged("smgimg");
					this.OnsmgimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smgvioe", DbType="VarChar(MAX)")]
		public string smgvioe
		{
			get
			{
				return this._smgvioe;
			}
			set
			{
				if ((this._smgvioe != value))
				{
					this.OnsmgvioeChanging(value);
					this.SendPropertyChanging();
					this._smgvioe = value;
					this.SendPropertyChanged("smgvioe");
					this.OnsmgvioeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fromTime", DbType="NVarChar(50)")]
		public string fromTime
		{
			get
			{
				return this._fromTime;
			}
			set
			{
				if ((this._fromTime != value))
				{
					this.OnfromTimeChanging(value);
					this.SendPropertyChanging();
					this._fromTime = value;
					this.SendPropertyChanged("fromTime");
					this.OnfromTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toTime", DbType="NVarChar(50)")]
		public string toTime
		{
			get
			{
				return this._toTime;
			}
			set
			{
				if ((this._toTime != value))
				{
					this.OntoTimeChanging(value);
					this.SendPropertyChanging();
					this._toTime = value;
					this.SendPropertyChanged("toTime");
					this.OntoTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.companyTable")]
	public partial class companyTable
	{
		
		private System.Nullable<int> _companyID;
		
		private string _userID;
		
		private string _companyName;
		
		private string _companyType;
		
		private System.Nullable<int> _companyCount;
		
		private string _describe;
		
		public companyTable()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyID", DbType="Int")]
		public System.Nullable<int> companyID
		{
			get
			{
				return this._companyID;
			}
			set
			{
				if ((this._companyID != value))
				{
					this._companyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="VarChar(50)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this._userID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyName", DbType="VarChar(50)")]
		public string companyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				if ((this._companyName != value))
				{
					this._companyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyType", DbType="VarChar(32)")]
		public string companyType
		{
			get
			{
				return this._companyType;
			}
			set
			{
				if ((this._companyType != value))
				{
					this._companyType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyCount", DbType="Int")]
		public System.Nullable<int> companyCount
		{
			get
			{
				return this._companyCount;
			}
			set
			{
				if ((this._companyCount != value))
				{
					this._companyCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_describe", DbType="VarChar(MAX)")]
		public string describe
		{
			get
			{
				return this._describe;
			}
			set
			{
				if ((this._describe != value))
				{
					this._describe = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jobTable")]
	public partial class jobTable
	{
		
		private System.Nullable<int> _jobID;
		
		private string _userID;
		
		private System.Nullable<int> _companyID;
		
		private string _position;
		
		private string _beginTime;
		
		private string _endTime;
		
		private string _describe;
		
		public jobTable()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobID", DbType="Int")]
		public System.Nullable<int> jobID
		{
			get
			{
				return this._jobID;
			}
			set
			{
				if ((this._jobID != value))
				{
					this._jobID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="VarChar(50)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this._userID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyID", DbType="Int")]
		public System.Nullable<int> companyID
		{
			get
			{
				return this._companyID;
			}
			set
			{
				if ((this._companyID != value))
				{
					this._companyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(32)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beginTime", DbType="VarChar(50)")]
		public string beginTime
		{
			get
			{
				return this._beginTime;
			}
			set
			{
				if ((this._beginTime != value))
				{
					this._beginTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endTime", DbType="VarChar(50)")]
		public string endTime
		{
			get
			{
				return this._endTime;
			}
			set
			{
				if ((this._endTime != value))
				{
					this._endTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_describe", DbType="VarChar(MAX)")]
		public string describe
		{
			get
			{
				return this._describe;
			}
			set
			{
				if ((this._describe != value))
				{
					this._describe = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.positionInfo")]
	public partial class positionInfo
	{
		
		private System.Nullable<int> _posID;
		
		private string _userID;
		
		private System.Nullable<int> _companyID;
		
		private string _posName;
		
		private string _createTime;
		
		private System.Nullable<int> _region;
		
		private System.Nullable<int> _city;
		
		private System.Nullable<int> _province;
		
		private string _record;
		
		private System.Nullable<int> _recruitment;
		
		private string _range;
		
		private System.Nullable<int> _posstate;
		
		private string _posType;
		
		private string _requirements;
		
		public positionInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posID", DbType="Int")]
		public System.Nullable<int> posID
		{
			get
			{
				return this._posID;
			}
			set
			{
				if ((this._posID != value))
				{
					this._posID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="VarChar(50)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this._userID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyID", DbType="Int")]
		public System.Nullable<int> companyID
		{
			get
			{
				return this._companyID;
			}
			set
			{
				if ((this._companyID != value))
				{
					this._companyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posName", DbType="VarChar(50)")]
		public string posName
		{
			get
			{
				return this._posName;
			}
			set
			{
				if ((this._posName != value))
				{
					this._posName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createTime", DbType="VarChar(50)")]
		public string createTime
		{
			get
			{
				return this._createTime;
			}
			set
			{
				if ((this._createTime != value))
				{
					this._createTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="Int")]
		public System.Nullable<int> region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="Int")]
		public System.Nullable<int> city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="Int")]
		public System.Nullable<int> province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this._province = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record", DbType="VarChar(32)")]
		public string record
		{
			get
			{
				return this._record;
			}
			set
			{
				if ((this._record != value))
				{
					this._record = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recruitment", DbType="Int")]
		public System.Nullable<int> recruitment
		{
			get
			{
				return this._recruitment;
			}
			set
			{
				if ((this._recruitment != value))
				{
					this._recruitment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_range", DbType="VarChar(100)")]
		public string range
		{
			get
			{
				return this._range;
			}
			set
			{
				if ((this._range != value))
				{
					this._range = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posstate", DbType="Int")]
		public System.Nullable<int> posstate
		{
			get
			{
				return this._posstate;
			}
			set
			{
				if ((this._posstate != value))
				{
					this._posstate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posType", DbType="VarChar(MAX)")]
		public string posType
		{
			get
			{
				return this._posType;
			}
			set
			{
				if ((this._posType != value))
				{
					this._posType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requirements", DbType="VarChar(MAX)")]
		public string requirements
		{
			get
			{
				return this._requirements;
			}
			set
			{
				if ((this._requirements != value))
				{
					this._requirements = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.projectTable")]
	public partial class projectTable
	{
		
		private System.Nullable<int> _projectID;
		
		private string _userID;
		
		private string _projectName;
		
		private string _projectType;
		
		private string _beginTime;
		
		private string _endTime;
		
		private string _describe;
		
		private string _duties;
		
		public projectTable()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectID", DbType="Int")]
		public System.Nullable<int> projectID
		{
			get
			{
				return this._projectID;
			}
			set
			{
				if ((this._projectID != value))
				{
					this._projectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="VarChar(50)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this._userID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectName", DbType="VarChar(50)")]
		public string projectName
		{
			get
			{
				return this._projectName;
			}
			set
			{
				if ((this._projectName != value))
				{
					this._projectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectType", DbType="VarChar(32)")]
		public string projectType
		{
			get
			{
				return this._projectType;
			}
			set
			{
				if ((this._projectType != value))
				{
					this._projectType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beginTime", DbType="VarChar(50)")]
		public string beginTime
		{
			get
			{
				return this._beginTime;
			}
			set
			{
				if ((this._beginTime != value))
				{
					this._beginTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endTime", DbType="VarChar(50)")]
		public string endTime
		{
			get
			{
				return this._endTime;
			}
			set
			{
				if ((this._endTime != value))
				{
					this._endTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_describe", DbType="VarChar(MAX)")]
		public string describe
		{
			get
			{
				return this._describe;
			}
			set
			{
				if ((this._describe != value))
				{
					this._describe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duties", DbType="VarChar(MAX)")]
		public string duties
		{
			get
			{
				return this._duties;
			}
			set
			{
				if ((this._duties != value))
				{
					this._duties = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.regionTable")]
	public partial class regionTable
	{
		
		private System.Nullable<int> _provinceID;
		
		private string _provinceName;
		
		private System.Nullable<int> _cityID;
		
		private string _cityName;
		
		private System.Nullable<int> _regionID;
		
		private string _regionName;
		
		public regionTable()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provinceID", DbType="Int")]
		public System.Nullable<int> provinceID
		{
			get
			{
				return this._provinceID;
			}
			set
			{
				if ((this._provinceID != value))
				{
					this._provinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provinceName", DbType="VarChar(32)")]
		public string provinceName
		{
			get
			{
				return this._provinceName;
			}
			set
			{
				if ((this._provinceName != value))
				{
					this._provinceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityID", DbType="Int")]
		public System.Nullable<int> cityID
		{
			get
			{
				return this._cityID;
			}
			set
			{
				if ((this._cityID != value))
				{
					this._cityID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityName", DbType="VarChar(32)")]
		public string cityName
		{
			get
			{
				return this._cityName;
			}
			set
			{
				if ((this._cityName != value))
				{
					this._cityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionID", DbType="Int")]
		public System.Nullable<int> regionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				if ((this._regionID != value))
				{
					this._regionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionName", DbType="VarChar(32)")]
		public string regionName
		{
			get
			{
				return this._regionName;
			}
			set
			{
				if ((this._regionName != value))
				{
					this._regionName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.resume")]
	public partial class resume
	{
		
		private System.Nullable<int> _resumeID;
		
		private string _userID;
		
		private string _jobState;
		
		private string _resumeState;
		
		private string _myEdu;
		
		private string _jobYear;
		
		private string _toAddress;
		
		private string _industry;
		
		private string _position;
		
		private string _salary;
		
		private string _research;
		
		private System.Nullable<int> _jobID;
		
		private System.Nullable<int> _projectID;
		
		public resume()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeID", DbType="Int")]
		public System.Nullable<int> resumeID
		{
			get
			{
				return this._resumeID;
			}
			set
			{
				if ((this._resumeID != value))
				{
					this._resumeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="VarChar(50)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this._userID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobState", DbType="VarChar(32)")]
		public string jobState
		{
			get
			{
				return this._jobState;
			}
			set
			{
				if ((this._jobState != value))
				{
					this._jobState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeState", DbType="VarChar(32)")]
		public string resumeState
		{
			get
			{
				return this._resumeState;
			}
			set
			{
				if ((this._resumeState != value))
				{
					this._resumeState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_myEdu", DbType="VarChar(32)")]
		public string myEdu
		{
			get
			{
				return this._myEdu;
			}
			set
			{
				if ((this._myEdu != value))
				{
					this._myEdu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobYear", DbType="VarChar(32)")]
		public string jobYear
		{
			get
			{
				return this._jobYear;
			}
			set
			{
				if ((this._jobYear != value))
				{
					this._jobYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toAddress", DbType="VarChar(MAX)")]
		public string toAddress
		{
			get
			{
				return this._toAddress;
			}
			set
			{
				if ((this._toAddress != value))
				{
					this._toAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_industry", DbType="VarChar(32)")]
		public string industry
		{
			get
			{
				return this._industry;
			}
			set
			{
				if ((this._industry != value))
				{
					this._industry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(32)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(32)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this._salary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_research", DbType="VarChar(MAX)")]
		public string research
		{
			get
			{
				return this._research;
			}
			set
			{
				if ((this._research != value))
				{
					this._research = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobID", DbType="Int")]
		public System.Nullable<int> jobID
		{
			get
			{
				return this._jobID;
			}
			set
			{
				if ((this._jobID != value))
				{
					this._jobID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectID", DbType="Int")]
		public System.Nullable<int> projectID
		{
			get
			{
				return this._projectID;
			}
			set
			{
				if ((this._projectID != value))
				{
					this._projectID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.resumeJob")]
	public partial class resumeJob
	{
		
		private System.Nullable<int> _resumeID;
		
		private System.Nullable<int> _jobID;
		
		public resumeJob()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeID", DbType="Int")]
		public System.Nullable<int> resumeID
		{
			get
			{
				return this._resumeID;
			}
			set
			{
				if ((this._resumeID != value))
				{
					this._resumeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobID", DbType="Int")]
		public System.Nullable<int> jobID
		{
			get
			{
				return this._jobID;
			}
			set
			{
				if ((this._jobID != value))
				{
					this._jobID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.resumePoject")]
	public partial class resumePoject
	{
		
		private System.Nullable<int> _resumeID;
		
		private System.Nullable<int> _pojectID;
		
		public resumePoject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeID", DbType="Int")]
		public System.Nullable<int> resumeID
		{
			get
			{
				return this._resumeID;
			}
			set
			{
				if ((this._resumeID != value))
				{
					this._resumeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pojectID", DbType="Int")]
		public System.Nullable<int> pojectID
		{
			get
			{
				return this._pojectID;
			}
			set
			{
				if ((this._pojectID != value))
				{
					this._pojectID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
